"""Emit the Appendix-F raw-data tables behind every 1-D comparison figure
-> paper/tables/tab_*.tex (booktabs fragments, \\input by the appendix).

  tab_flatplate_onsets : fig:flatplate_batch bottom panels (chi=1 and c_v1
                         crossing Re_theta vs AGS, Flow360 + OpenFOAM)
  tab_nlf_data         : figs nlfaft/nlfpolar/nlfnegalpha (CL, CD, x_tr)
  tab_openfoam_nlf     : the steel-blue OpenFOAM L1 overlay of figs
                         nlfaft/nlfpolar
  tab_eppler_polar     : fig:epppolar (CL, CD, all ten incidences)
  tab_eppler_bubble    : fig:eppbubble (x_LS, x_R)
  tab_eppler_resweep   : fig:eppresweepforces (cl, cd, x_sep, x_R vs Re)

Data sources are the committed campaign JSONs, the figure scripts' own
station dumps (eppbubble_stations_computed.json,
eppresweep_forces_computed.json — regenerated by their figure scripts), the
OpenFOAM summary JSON, and the case force histories for the L2-only Eppler
extension incidences. Missing cases print '--'.

Run from paper/: python3 repro/cfd/emit_appendix_tables.py
"""
import csv
import json
import os
import sys

import numpy as np

_H = os.path.dirname(os.path.abspath(__file__))
PAPER = os.path.abspath(os.path.join(_H, '..', '..'))
B = os.environ.get("SAAI_CFD_ROOT", "/home/qiqi/flexcompute/sa-ai/flow360_fv1")
TAB = os.path.join(PAPER, 'tables')
os.makedirs(TAB, exist_ok=True)
sys.path.insert(0, _H)


def fmt(v, nd=4):
    return '--' if v is None or (isinstance(v, float) and not np.isfinite(v)) \
        else f'{v:.{nd}f}'


def write(name, header, rows, caption, label, align):
    p = os.path.join(TAB, name)
    with open(p, 'w') as f:
        f.write('\\begin{table}[tp]\n  \\centering\\small\n'
                f'  \\caption{{{caption}}}\n  \\label{{{label}}}\n'
                f'  \\begin{{tabular}}{{{align}}}\n    \\toprule\n'
                f'    {header} \\\\\n    \\midrule\n')
        for r in rows:
            f.write(f'    {r} \\\\\n')
        f.write('    \\bottomrule\n  \\end{tabular}\n\\end{table}\n')
    print('wrote', p)


def tail_forces(d):
    try:
        rows = [r for r in list(csv.reader(open(f"{d}/total_forces_v2.csv")))[1:]
                if len(r) > 3]
        t = rows[int(0.8 * len(rows)):]
        return (float(np.median([float(r[2]) for r in t])),
                float(np.median([float(r[3]) for r in t])))
    except (FileNotFoundError, IndexError):
        return None, None


# ---------------- flat plate ------------------------------------------------
def flatplate():
    import regen_flatplate_flow360 as FP

    def crossings(x, chimax, reth):
        m = np.isfinite(chimax) & np.isfinite(reth)
        xs, cs, rs = x[m], chimax[m], reth[m]
        out = []
        for lev in (1.0, FP.C_V1):
            hits = np.where(cs > lev)[0]
            if not len(hits) or hits[0] == 0:
                out.append(None)
                continue
            i = hits[0]
            f = (lev - cs[i-1]) / (cs[i] - cs[i-1])
            out.append(float(rs[i-1] + f * (rs[i] - rs[i-1])))
        return out

    of = json.load(open(f'{PAPER}/data/openfoam_flatplate_summary.json'))['cases']
    rows = []
    for tu in FP.TU_LIST:
        x, reth, cf, chimax, _, _ = FP.cf_and_retheta(FP.case_dir(tu))
        c1, cv = crossings(x, chimax, reth)
        e = of[f'{tu:.2f}']
        ox = np.array(e['x'], float)
        ochi = np.array([np.nan if v is None else v for v in e['chi_max']])
        oreth = np.array([np.nan if v is None else v for v in e['Re_theta']])
        o1, ov = crossings(ox, ochi, oreth)
        ags = FP.AGS_Reth(tu)
        rows.append(f'{tu:g} & {ags:.0f} & {fmt(c1, 0)} & {fmt(cv, 0)} & '
                    f'{fmt(o1, 0)} & {fmt(ov, 0)}')
    write('tab_flatplate_onsets.tex',
          r'$Tu$ [\%] & AGS $Re_\theta$ & $\chi\!=\!1$ & $\chi\!=\!c_{v1}$ &'
          r' OF $\chi\!=\!1$ & OF $\chi\!=\!c_{v1}$',
          rows,
          r'Flat-plate transition-onset $Re_\theta$ (integrated from the '
          r'computed profiles) at the $\chi\!=\!1$ and $\chi\!=\!c_{v1}$ '
          r'crossings, Flow360 and the OpenFOAM replication (OF), against '
          r'the Abu-Ghannam \& Shaw correlation '
          r'(Fig.~\ref{fig:flatplate_batch}).',
          'tab:data_flatplate', 'cccccc')


# ---------------- NLF -------------------------------------------------------
def nlf():
    camp = json.load(open(f'{B}/sphere_campaign_nlf_results.json'))
    for k, v in json.load(open(f'{B}/sphere_campaign_nlf_neg_results.json')).items():
        camp.setdefault(k, v)
    rows = []
    neg_missing = False
    for a, tag in ((-8, 'am8'), (-4, 'am4'), (0, 'a0'), (4, 'a4'),
                   (9, 'a9'), (15, 'a15')):
        for lev in ('L0', 'L1', 'L2'):
            cells = [f'${a}$ & {lev}']
            found = False
            for fam in ('str', 'cav'):
                key = f'{fam}{lev}prop_nlf0416_Re4M_{tag}'
                e = camp.get(key)
                if e:
                    found = True
                    cells.append(f"{fmt(e.get('CL'))} & {fmt(e.get('CD'), 5)} & "
                                 f"{fmt(e.get('xtr_up'), 3)} & {fmt(e.get('xtr_lo'), 3)}")
                else:
                    # only the negative pair may legitimately be absent on
                    # the coarser grids (runs staged); anything else is an
                    # error, not a shorter table
                    assert tag in ('am8', 'am4') and lev != 'L2', \
                        f'missing campaign record: {key}'
                    neg_missing = True
                    cells.append('-- & -- & -- & --')
            if found:
                rows.append(' & '.join(cells))
    negclause = (' The $-8^\\circ$/$-4^\\circ$ rows exist on the finest'
                 ' (L2) pair only.' if neg_missing else '')
    write('tab_nlf_data.tex',
          r'$\alpha$ & grid & \multicolumn{4}{c}{structured O-grid} &'
          r' \multicolumn{4}{c}{unstructured cavity} \\'
          r' & & $C_L$ & $C_D$ & $x_\mathrm{tr}^\mathrm{up}$ &'
          r' $x_\mathrm{tr}^\mathrm{lo}$ & $C_L$ & $C_D$ &'
          r' $x_\mathrm{tr}^\mathrm{up}$ & $x_\mathrm{tr}^\mathrm{lo}$',
          rows,
          r'NLF(1)-0416, $Re\!=\!4\!\times\!10^6$: computed forces and '
          r'transition locations behind '
          r'Figs.~\ref{fig:nlfaft}, \ref{fig:nlfpolar}, '
          r'and~\ref{fig:nlfnegalpha}.' + negclause,
          'tab:data_nlf', 'll cccc cccc')


# ---------------- OpenFOAM NLF (cross-solver overlay) ------------------------
def openfoam_nlf():
    """The L1 rows plotted as the steel-blue circles in figs nlfaft/nlfpolar.

    The overlay (and this table) is curated to L1, the converged family of
    the staged-protocol cross-solver runs: the OF L0 lower fronts include
    the same coarse-grid breakaway states the fig:nlfaft caption discusses
    for Flow360. Eppler columns are held until the port carries the fv1
    bypass (a model term there worth 5-10 counts) and its L2 lands.
    """
    of = json.load(open(f'{PAPER}/data/openfoam_airfoil_summary.json'))['cases']
    rows = []
    for a, tag in ((-8, 'am8'), (-4, 'am4'), (0, 'a0'), (4, 'a4'),
                   (9, 'a9'), (15, 'a15')):
        e = of[f'nlf_strL1_{tag}']
        assert e['alpha'] == a and e['level'] == 'L1'
        rows.append(f"${a}$ & {fmt(e['cl'])} & {fmt(e['cd'], 5)} & "
                    f"{fmt(e['xtr_up'], 3)} & {fmt(e['xtr_lo'], 3)}")
    write('tab_openfoam_nlf.tex',
          r'$\alpha$ & $C_L$ & $C_D$ & $x_\mathrm{tr}^\mathrm{up}$ &'
          r' $x_\mathrm{tr}^\mathrm{lo}$',
          rows,
          r'NLF(1)-0416, $Re\!=\!4\!\times\!10^6$: the independent '
          r'cell-centered incompressible (OpenFOAM) implementation on the '
          "paper's structured L1 grid---the steel-blue circles of "
          r'Figs.~\ref{fig:nlfaft} and~\ref{fig:nlfpolar}. Conventions as '
          r'in Table~\ref{tab:data_nlf}, with the transition locations '
          r'read from the OpenFOAM fields at the same near-wall '
          r'$\chi\!=\!1$ crossing; the port omits the bypass of '
          r'Eq.~\ref{eq:fv1bypass}.',
          'tab:data_openfoam_nlf', 'c cccc')


# ---------------- Eppler polar ----------------------------------------------
def eppler_polar():
    camp = json.load(open(f'{B}/sphere_campaign_eppler_results.json'))
    # the twelve extension cases have their own committed campaign record --
    # the authoritative values (the case CSVs are not shipped)
    for k, v in json.load(open(f'{B}/sphere_campaign_eppler_ext_results.json')).items():
        camp.setdefault(k, v)
    TAG = {-2: 'am2', 0: 'a0', 1: 'a1', 2: 'a2', 3: 'a3', 4: 'a4x',
           5: 'a5', 6: 'a6', 7: 'a7', 8.5: 'a8p5'}
    rows = []
    for a in (-2, 0, 1, 2, 3, 4, 5, 6, 7, 8.5):
        levs = ('L0', 'L1', 'L2') if a in (0, 2, 5, 7) else ('L2',)
        for lev in levs:
            cells = [f'${a:g}$ & {lev}']
            for fam in ('str', 'cav'):
                key = f'{fam}{lev}prop_eppler387_Re200k_{TAG[a]}'
                assert key in camp, f'missing campaign record: {key}'
                e = camp[key]
                cells.append(f"{fmt(e.get('CL'))} & {fmt(e.get('CD'), 5)}")
            rows.append(' & '.join(cells))
    write('tab_eppler_polar.tex',
          r'$\alpha$ & grid & \multicolumn{2}{c}{structured O-grid} &'
          r' \multicolumn{2}{c}{unstructured cavity} \\'
          r' & & $C_L$ & $C_D$ & $C_L$ & $C_D$',
          rows,
          r'Eppler 387, $Re\!=\!2\!\times\!10^5$: computed forces behind the '
          r'polar of Fig.~\ref{fig:epppolar} (the $-2^\circ$--$8.5^\circ$ '
          r'extension incidences exist on the finest pair only).',
          'tab:data_epppolar', 'll cc cc')


# ---------------- Eppler bubble stations -------------------------------------
def eppler_bubble():
    st = json.load(open(f'{PAPER}/data/eppbubble_stations_computed.json'))
    alphas = sorted({float(a) for d in st.values() for a in d}, key=float)
    rows = []
    for a in alphas:
        levs = ('L0', 'L1', 'L2') if a in (0, 2, 5, 7) else ('L2',)
        for lev in levs:
            cells = [f'${a:g}$ & {lev}']
            for fam in ('str', 'cav'):
                e = st.get(f'{fam}_{lev}', {}).get(f'{a:g}')
                if e:
                    cells.append(f'{fmt(e[0], 3)} & {fmt(e[1], 3)}')
                else:
                    cells.append('-- & --')
            rows.append(' & '.join(cells))
    write('tab_eppler_bubble.tex',
          r'$\alpha$ & grid & \multicolumn{2}{c}{structured O-grid} &'
          r' \multicolumn{2}{c}{unstructured cavity} \\'
          r' & & $x_{LS}/c$ & $x_R/c$ & $x_{LS}/c$ & $x_R/c$',
          rows,
          r'Eppler 387, $Re\!=\!2\!\times\!10^5$: computed upper-surface '
          r'laminar-separation and turbulent-reattachment stations behind '
          r'Fig.~\ref{fig:eppbubble} (signed-$C_f$ zero crossings; missing '
          r'entries transition ahead of separation and have no bubble). '
          r'The measured oil-flow reattachments (TM-4062 Table~III) at '
          r'$\alpha\!=\!0^\circ$/$2^\circ$/$5^\circ$ are '
          r'$0.74$/$0.67$/$0.59\,c$.',
          'tab:data_eppbubble', 'll cc cc')


# ---------------- Eppler Reynolds sweep ---------------------------------------
def eppler_resweep():
    st = json.load(open(f'{PAPER}/data/eppresweep_forces_computed.json'))
    rows = []
    for Rk in (60, 100, 200, 300, 460):
        for lev in ('L0', 'L1', 'L2'):
            cells = [f'${Rk}$k & {lev}']
            for fam in ('str', 'cav'):
                e = st[f'{fam}_{lev}'][str(Rk)]
                cells.append(f"{fmt(e['cl'])} & {fmt(e['cd'], 5)} & "
                             f"{fmt(e['xsep'], 3)} & {fmt(e['xr'], 3)}")
            rows.append(' & '.join(cells))
    write('tab_eppler_resweep.tex',
          r'$Re$ & grid & \multicolumn{4}{c}{structured O-grid} &'
          r' \multicolumn{4}{c}{unstructured cavity} \\'
          r' & & $c_l$ & $c_d$ & $x_\mathrm{sep}$ & $x_R$ &'
          r' $c_l$ & $c_d$ & $x_\mathrm{sep}$ & $x_R$',
          rows,
          r'Eppler 387 $\alpha\!=\!5^\circ$ Reynolds sweep: computed forces '
          r'and upper-surface stations behind Fig.~\ref{fig:eppresweepforces} '
          r'($x_R$ pinned near $1$ means no closure ahead of the trailing '
          r'edge; $c_m$ and the $e^9$/experiment columns are in '
          r'Table~\ref{tab:eppresweep}). The $2\times10^5$ rows are the '
          r'figure script\'s own re-extraction of the benchmark histories '
          r'and agree with Table~\ref{tab:data_epppolar}\'s campaign-record '
          r'values to within one unit in the last digit (tail-window '
          r'rounding).',
          'tab:data_eppresweep', 'll cccc cccc')


# ---------------- spheroid ----------------------------------------------------
# prose order: the low-Re ladder, the pure-TS anchors, the workshop pair
SPH_COND = [(1.5e6, '5', 'a5'), (1.5e6, '10', 'a10'), (1.5e6, '29.7', 'a29p7'),
            (7.2e6, '0', 're72a0'), (7.2e6, '2.5', 're72a2p5'),
            (6.5e6, '5', 're65a5'), (6.5e6, '10', 're65a10')]


def spheroid_totals():
    camp = json.load(open(f'{B}/sphere_campaign_spheroid_results.json'))
    rows = []
    for Re, alab, tag in SPH_COND:
        cells = [f'${Re/1e6:g}\\times10^6$ & ${alab}^\\circ$']
        for lev in ('L0', 'L1', 'L2'):
            e = camp.get(f'case_ogrid_{lev}_saai_{tag}')
            if e and e.get('complete'):
                cells.append(f"{fmt(e['CL'])} & {fmt(e['CD'], 5)}")
            else:
                cells.append('-- & --')
        # staged conditions keep their dash row: the caption's
        # 'dashes = in progress' must describe visible rows
        rows.append(' & '.join(cells))
    write('tab_spheroid_totals.tex',
          r'$Re_L$ & $\alpha$ & \multicolumn{2}{c}{L0} &'
          r' \multicolumn{2}{c}{L1} & \multicolumn{2}{c}{L2} \\'
          r' & & $C_L$ & $C_D$ & $C_L$ & $C_D$ & $C_L$ & $C_D$',
          rows,
          r'6:1 prolate spheroid totals (half-model, reference area = '
          r'frontal): SA-AI at every DFVLR-measured condition on the '
          r'L0--L2 O-grid ladder. Dashes: runs in progress.',
          'tab:sphtotals', 'll cc cc cc')


def spheroid_fronts():
    d = json.load(open(f'{PAPER}/data/spheroid_front_summary.json'))
    rows = []
    for r in d['rows']:
        rows.append(f"{r['phi']:.1f} & {fmt(r['meas'], 3)} & "
                    f"{fmt(r['cf_L0'], 3)} & {fmt(r['cf_L1'], 3)} & "
                    f"{fmt(r['cf_L2'], 3)} & "
                    f"[{fmt(r['band_lo'], 3)}, {fmt(r['band_hi'], 3)}] & "
                    f"{fmt(r['chi1_L2'], 3)} & {fmt(r['cv1_L2'], 3)}")
    write('tab_spheroid_fronts.tex',
          r'$\phi$ [deg] & measured & \multicolumn{3}{c}{$C_f$-rise, '
          r'$k\!=\!1.5$} & L2 band & $\chi\!=\!1$ & $\chi\!=\!c_{v1}$ \\'
          r' & $x/L$ & L0 & L1 & L2 & $k\!=\!1.25$--$2$ & L2 & L2',
          rows,
          r'6:1 prolate spheroid, $Re_L\!=\!1.5\times10^6$ (measured '
          r'$1.52\times10^6$), $\alpha\!=\!10^\circ$: computed front '
          r'stations behind Fig.~\ref{fig:spheroidfront} at the measured '
          r'azimuths (DFVLR hot films, Stock Fig.~15a).',
          'tab:data_spheroid', 'cc ccc c cc')


if __name__ == '__main__':
    flatplate()
    nlf()
    openfoam_nlf()
    eppler_polar()
    eppler_bubble()
    eppler_resweep()
    spheroid_totals()
    spheroid_fronts()
    print('APPENDIX-TABLES-DONE')
