"""Emit the Appendix-F raw-data tables behind every 1-D comparison figure
-> paper/tables/tab_*.tex (booktabs fragments, \\input by the appendix).

  tab_flatplate_onsets : fig:flatplate_batch bottom panels (chi=1 and c_v1
                         crossing Re_theta vs AGS, Flow360 + OpenFOAM)
  tab_nlf_data         : figs nlfaft/nlfpolar/nlfnegalpha (CL, CD, x_tr)
  tab_eppler_polar     : fig:epppolar (CL, CD, all ten incidences)
  tab_eppler_bubble    : fig:eppbubble (x_LS, x_R)
  tab_eppler_resweep   : fig:eppresweepforces (cl, cd, x_sep, x_R vs Re)

Data sources are the committed campaign JSONs, the figure scripts' own
station dumps (eppbubble_stations_computed.json,
eppresweep_forces_computed.json — regenerated by their figure scripts), the
OpenFOAM summary JSON, and the case force histories for the L2-only Eppler
extension incidences. Missing cases print '--'.

Run from paper/: python3 repro/cfd/emit_appendix_tables.py
"""
import csv
import json
import os
import sys

import numpy as np

_H = os.path.dirname(os.path.abspath(__file__))
PAPER = os.path.abspath(os.path.join(_H, '..', '..'))
B = os.environ.get("SAAI_CFD_ROOT", "/home/qiqi/flexcompute/sa-ai/flow360_fv1")
TAB = os.path.join(PAPER, 'tables')
os.makedirs(TAB, exist_ok=True)
sys.path.insert(0, _H)


def fmt(v, nd=4):
    return '--' if v is None or (isinstance(v, float) and not np.isfinite(v)) \
        else f'{v:.{nd}f}'


def write(name, header, rows, caption, label, align):
    p = os.path.join(TAB, name)
    with open(p, 'w') as f:
        f.write('\\begin{table}[tp]\n  \\centering\\small\n'
                f'  \\caption{{{caption}}}\n  \\label{{{label}}}\n'
                f'  \\begin{{tabular}}{{{align}}}\n    \\toprule\n'
                f'    {header} \\\\\n    \\midrule\n')
        for r in rows:
            f.write(f'    {r} \\\\\n')
        f.write('    \\bottomrule\n  \\end{tabular}\n\\end{table}\n')
    print('wrote', p)


def tail_forces(d):
    try:
        rows = [r for r in list(csv.reader(open(f"{d}/total_forces_v2.csv")))[1:]
                if len(r) > 3]
        t = rows[int(0.8 * len(rows)):]
        return (float(np.median([float(r[2]) for r in t])),
                float(np.median([float(r[3]) for r in t])))
    except (FileNotFoundError, IndexError):
        return None, None


# ---------------- flat plate ------------------------------------------------
def flatplate():
    import regen_flatplate_flow360 as FP

    def crossings(x, chimax, reth):
        m = np.isfinite(chimax) & np.isfinite(reth)
        xs, cs, rs = x[m], chimax[m], reth[m]
        out = []
        for lev in (1.0, FP.C_V1):
            hits = np.where(cs > lev)[0]
            if not len(hits) or hits[0] == 0:
                out.append(None)
                continue
            i = hits[0]
            f = (lev - cs[i-1]) / (cs[i] - cs[i-1])
            out.append(float(rs[i-1] + f * (rs[i] - rs[i-1])))
        return out

    of = json.load(open(f'{PAPER}/data/openfoam_flatplate_summary.json'))['cases']
    rows = []
    for tu in FP.TU_LIST:
        x, reth, cf, chimax, _, _ = FP.cf_and_retheta(FP.case_dir(tu))
        c1, cv = crossings(x, chimax, reth)
        e = of[f'{tu:.2f}']
        ox = np.array(e['x'], float)
        ochi = np.array([np.nan if v is None else v for v in e['chi_max']])
        oreth = np.array([np.nan if v is None else v for v in e['Re_theta']])
        o1, ov = crossings(ox, ochi, oreth)
        ags = FP.AGS_Reth(tu)
        rows.append(f'{tu:g} & {ags:.0f} & {fmt(c1, 0)} & {fmt(cv, 0)} & '
                    f'{fmt(o1, 0)} & {fmt(ov, 0)}')
    write('tab_flatplate_onsets.tex',
          r'$Tu$ [\%] & AGS $Re_\theta$ & $\chi\!=\!1$ & $\chi\!=\!c_{v1}$ &'
          r' OF $\chi\!=\!1$ & OF $\chi\!=\!c_{v1}$',
          rows,
          r'Flat-plate transition-onset $Re_\theta$ (integrated from the '
          r'computed profiles) at the $\chi\!=\!1$ and $\chi\!=\!c_{v1}$ '
          r'crossings, Flow360 and the OpenFOAM replication (OF), against '
          r'the Abu-Ghannam \& Shaw correlation '
          r'(Fig.~\ref{fig:flatplate_batch}).',
          'tab:data_flatplate', 'cccccc')


# ---------------- NLF -------------------------------------------------------
def nlf():
    camp = json.load(open(f'{B}/sphere_campaign_nlf_results.json'))
    for k, v in json.load(open(f'{B}/sphere_campaign_nlf_neg_results.json')).items():
        camp.setdefault(k, v)
    rows = []
    for a, tag in ((-8, 'am8'), (-4, 'am4'), (0, 'a0'), (4, 'a4'),
                   (9, 'a9'), (15, 'a15')):
        for lev in ('L0', 'L1', 'L2'):
            cells = [f'${a}$ & {lev}']
            found = False
            for fam in ('str', 'cav'):
                e = camp.get(f'{fam}{lev}prop_nlf0416_Re4M_{tag}')
                if e:
                    found = True
                    cells.append(f"{fmt(e.get('CL'))} & {fmt(e.get('CD'), 5)} & "
                                 f"{fmt(e.get('xtr_up'), 3)} & {fmt(e.get('xtr_lo'), 3)}")
                else:
                    cells.append('-- & -- & -- & --')
            if found:
                rows.append(' & '.join(cells))
    write('tab_nlf_data.tex',
          r'$\alpha$ & grid & \multicolumn{4}{c}{structured O-grid} &'
          r' \multicolumn{4}{c}{unstructured cavity} \\'
          r' & & $C_L$ & $C_D$ & $x_\mathrm{tr}^\mathrm{up}$ &'
          r' $x_\mathrm{tr}^\mathrm{lo}$ & $C_L$ & $C_D$ &'
          r' $x_\mathrm{tr}^\mathrm{up}$ & $x_\mathrm{tr}^\mathrm{lo}$',
          rows,
          r'NLF(1)-0416, $Re\!=\!4\!\times\!10^6$: computed forces and '
          r'transition locations behind '
          r'Figs.~\ref{fig:nlfaft}, \ref{fig:nlfpolar}, '
          r'and~\ref{fig:nlfnegalpha}.',
          'tab:data_nlf', 'll cccc cccc')


# ---------------- Eppler polar ----------------------------------------------
def eppler_polar():
    camp = json.load(open(f'{B}/sphere_campaign_eppler_results.json'))
    TAG = {-2: 'am2', 0: 'a0', 1: 'a1', 2: 'a2', 3: 'a3', 4: 'a4x',
           5: 'a5', 6: 'a6', 7: 'a7', 8.5: 'a8p5'}
    rows = []
    for a in (-2, 0, 1, 2, 3, 4, 5, 6, 7, 8.5):
        levs = ('L0', 'L1', 'L2') if a in (0, 2, 5, 7) else ('L2',)
        for lev in levs:
            cells = [f'${a:g}$ & {lev}']
            for fam in ('str', 'cav'):
                key = f'{fam}{lev}prop_eppler387_Re200k_{TAG[a]}'
                e = camp.get(key)
                if e:
                    cells.append(f"{fmt(e.get('CL'))} & {fmt(e.get('CD'), 5)}")
                else:
                    cl, cd = tail_forces(f'{B}/{key}')
                    cells.append(f'{fmt(cl)} & {fmt(cd, 5)}')
            rows.append(' & '.join(cells))
    write('tab_eppler_polar.tex',
          r'$\alpha$ & grid & \multicolumn{2}{c}{structured O-grid} &'
          r' \multicolumn{2}{c}{unstructured cavity} \\'
          r' & & $C_L$ & $C_D$ & $C_L$ & $C_D$',
          rows,
          r'Eppler 387, $Re\!=\!2\!\times\!10^5$: computed forces behind the '
          r'polar of Fig.~\ref{fig:epppolar} (the $-2^\circ$--$8.5^\circ$ '
          r'extension incidences exist on the finest pair only).',
          'tab:data_epppolar', 'll cc cc')


# ---------------- Eppler bubble stations -------------------------------------
def eppler_bubble():
    st = json.load(open(f'{PAPER}/data/eppbubble_stations_computed.json'))
    alphas = sorted({float(a) for d in st.values() for a in d}, key=float)
    rows = []
    for a in alphas:
        levs = ('L0', 'L1', 'L2') if a in (0, 2, 5, 7) else ('L2',)
        for lev in levs:
            cells = [f'${a:g}$ & {lev}']
            for fam in ('str', 'cav'):
                e = st.get(f'{fam}_{lev}', {}).get(f'{a:g}')
                if e:
                    cells.append(f'{fmt(e[0], 3)} & {fmt(e[1], 3)}')
                else:
                    cells.append('-- & --')
            rows.append(' & '.join(cells))
    write('tab_eppler_bubble.tex',
          r'$\alpha$ & grid & \multicolumn{2}{c}{structured O-grid} &'
          r' \multicolumn{2}{c}{unstructured cavity} \\'
          r' & & $x_{LS}/c$ & $x_R/c$ & $x_{LS}/c$ & $x_R/c$',
          rows,
          r'Eppler 387, $Re\!=\!2\!\times\!10^5$: computed upper-surface '
          r'laminar-separation and turbulent-reattachment stations behind '
          r'Fig.~\ref{fig:eppbubble} (signed-$C_f$ zero crossings; missing '
          r'entries transition ahead of separation and have no bubble).',
          'tab:data_eppbubble', 'll cc cc')


# ---------------- Eppler Reynolds sweep ---------------------------------------
def eppler_resweep():
    st = json.load(open(f'{PAPER}/data/eppresweep_forces_computed.json'))
    rows = []
    for Rk in (60, 100, 200, 300, 460):
        for lev in ('L0', 'L1', 'L2'):
            cells = [f'${Rk}$k & {lev}']
            for fam in ('str', 'cav'):
                e = st[f'{fam}_{lev}'][str(Rk)]
                cells.append(f"{fmt(e['cl'])} & {fmt(e['cd'], 5)} & "
                             f"{fmt(e['xsep'], 3)} & {fmt(e['xr'], 3)}")
            rows.append(' & '.join(cells))
    write('tab_eppler_resweep.tex',
          r'$Re$ & grid & \multicolumn{4}{c}{structured O-grid} &'
          r' \multicolumn{4}{c}{unstructured cavity} \\'
          r' & & $c_l$ & $c_d$ & $x_\mathrm{sep}$ & $x_R$ &'
          r' $c_l$ & $c_d$ & $x_\mathrm{sep}$ & $x_R$',
          rows,
          r'Eppler 387 $\alpha\!=\!5^\circ$ Reynolds sweep: computed forces '
          r'and upper-surface stations behind Fig.~\ref{fig:eppresweepforces} '
          r'($x_R$ pinned near $1$ means no closure ahead of the trailing '
          r'edge; $c_m$ and the $e^9$/experiment columns are in '
          r'Table~\ref{tab:eppresweep}).',
          'tab:data_eppresweep', 'll cccc cccc')


if __name__ == '__main__':
    flatplate()
    nlf()
    eppler_polar()
    eppler_bubble()
    eppler_resweep()
    print('APPENDIX-TABLES-DONE')
